services:
  facephi-postgres:
    container_name: facephi-postgres
    hostname: facephi-postgres
    image: postgres:12.13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
